# Generated by Django 4.1.5 on 2023-01-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Debito"),
                            (2, "Boleto"),
                            (3, "Financiamento"),
                            (4, "Crédito"),
                            (5, "Recebimento Empréstimo"),
                            (6, "Vendas"),
                            (7, "Recebimento Ted"),
                            (8, "Recebimento Doc"),
                            (9, "Aluguel"),
                        ]
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cpf", models.TextField(max_length=11)),
                ("card", models.TextField(max_length=12)),
                ("hour", models.TimeField()),
                ("owner_shop", models.TextField(max_length=14)),
                ("name_shop", models.TextField(max_length=19)),
            ],
        ),
    ]
