# Generated by Django 4.1.5 on 2023-01-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cnab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnab", models.FileField(upload_to="./uploads/")),
            ],
        ),
    ]
